title: katy.log
baseURL: https://blog.katech.jp/
languageCode: jp
theme: stack

params:
  dateFormat:
    published: "2006-01-02 15:04:05-07:00"
    lastUpdated: "2006-01-02 15:04:05-07:00"
  favicon: /images/favicon.ico
  article:
    toc: true
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: search
      - type: toc

permalinks:
  post: /posts/:filename/
  page: /:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    tabWidth: 4
